---

# useful when ansible_connection != ssh => (can't use rsync and synchronize)
- name: copy dotfiles to target host user account
  command: lxc file push --recursive --create-dirs {{item.home|default(users_defaults.home)}}/{{item.name}}/{{item.dotfiles_dir}} {{ansible_hostname}}{{item.home|default(users_defaults.home)}}/{{item.name}}
  delegate_to: localhost
  loop: "{{users|selectattr('dotfiles_dir','defined')|list}}"
  when:
    - cm_user == a_cm_user
  vars:
    cm_user: "{{users_usermap.get(item['name'], item['name'])}}"

- name: copy vimdir to target host user account
  command: lxc file push --recursive --create-dirs {{item.home|default(users_defaults.home)}}/{{item.name}}/{{item.vim_dir}} {{ansible_hostname}}{{item.home|default(users_defaults.home)}}/{{item.name}}
  delegate_to: localhost
  loop: "{{users|selectattr('vim_dir','defined')|list}}"
  when:
    - cm_user == a_cm_user
  vars:
    cm_user: "{{users_usermap.get(item['name'], item['name'])}}"

# fixme: you can only connect as root with lxd connection
- name: adjust home folders perms (after lxd file push)
  file:
    path: "{{item.home|default(users_defaults.home)}}"
    recurse: yes
    owner: "{{item['name']}}"
    group: "{{usergroup['name']}}"
  loop: "{{users|default(omit)}}"
  when:
    - cm_user == a_cm_user
  vars:
    cm_user: "{{users_usermap.get(item['name'], item['name'])}}"
