---

# useful when ansible_connection != ssh => (can't use rsync and synchronize)
- name: copy dotfiles to target host user account
  command: >
    lxc file push --recursive --create-dirs
    {{item['homedir_root']|default(users_defaults['homedir_root'] ~ '/' ~ item.name)}}/{{item.dotfiles_dir}}
    {{ansible_hostname}}/{{item['homedir_root']|default(users_defaults['homedir_root'] ~ '/' ~ item.name)}}
  delegate_to: localhost
  loop: "{{users|selectattr('dotfiles_dir','defined')|list}}"
  when:
    - cm_user == a_cm_user
  vars:
    cm_user: "{{users_usermap.get(item['name'], item['name'])}}"

- name: copy vimdir to target host user account
  command: >
    lxc file push --recursive --create-dirs
    {{item['homedir']|default(users_defaults['homedir_root'] ~ '/' ~ item.name)}}/{{item['vim_dir']}}
    {{ansible_hostname}}/{{item['homedir_root']|default(users_defaults['homedir_root'] ~ '/' ~ item['name'])}}
  delegate_to: localhost
  loop: "{{users|selectattr('vim_dir','defined')|list}}"
  when:
    - cm_user == a_cm_user
  vars:
    cm_user: "{{users_usermap.get(item['name'], item['name'])}}"

# fixme: you can only connect as root with lxd connection
- name: adjust 'homedir' folders perms (after lxd file push)
  file:
    path: "{{item['homedir']|default(users_defaults['homedir_root'] ~ '/' ~ item['name'])}}"
    recurse: yes
    owner: "{{item['name']}}"
    group: "{{usergroup['name']}}"
  loop: "{{users|default(omit)}}"
  when:
    - cm_user == a_cm_user
  vars:
    cm_user: "{{users_usermap.get(item['name'], item['name'])}}"
