---

# useful fallback when ansible_connection != ssh => (can't use rsync//synchronize)
- name: copy dotfiles to target host user account
  copy:
    src: "{{item['homedir']|default(users_defaults['homedir_root'] ~ '/' ~ cm_user)}}/{{item['dotfiles_dir']}}"
    dest: "{{item['homedir']|default(users_defaults['homedir_root'] ~ '/' ~ item['name'])}}/"
    owner: "{{item['name']}}"
    group: "{{usergroup['name']}}"
  loop: "{{users|selectattr('dotfiles_dir','defined')|list}}"
  when:
    - cm_user == a_cm_user
  vars:
    cm_user: "{{users_usermap.get(item['name'], item['name'])}}"

- name: copy .vim directory to target host user account
  copy:
    src: "{{item['homedir']|default(users_defaults['homedir_root'] ~ '/' ~ cm_user)}}/{{item['vim_dir']}}"
    dest: "{{item['homedir']|default(users_defaults['homedir_root'] ~ '/' ~ item['name'])}}/"
    owner: "{{item['name']}}"
    group: "{{usergroup['name']}}"
  loop: "{{users|selectattr('vim_dir','defined')|list}}"
  when:
    - cm_user == a_cm_user
  vars:
    cm_user: "{{users_usermap.get(item['name'], item['name'])}}"
