---

# included from multiples places, therefore content must remain in this task
# file
#
# As each user might have to install his previously generated ssh public key to
# the public git remote server before cloning or use https..

# # option #1: git module and www access
# - name: pull dotfiles repo with git module
#   git:
#     accept_hostkey: yes
#     clone: yes
#     recursive: yes
#     repo: "{{item['dotfiles_repo']}}"
#     dest: "{{item['home']|default(users_defaults['home'])}}/{{item['name']}}/dotfiles"
#   loop: "{{users|selectattr('dotfiles_repo','defined')|list}}"

# option #2: push from CM when no www access
#   Alternatively, if target has no www access or for whatever other reasons,
#   you can than at least sync useful stuff from a dir on the control
#   machine.

- block:
  ## option: #2a: ssh is available
  - import_tasks: account_dotfiles_rsync.yml
    when:
      - (ansible_connection is undefined or ansible_connection == "ssh" or ansible_connection == "smart")
  ## option: #2b: ssh is not available
  - import_tasks: account_dotfiles_copy.yml
    when:
      - ansible_connection is defined and ansible_connection != "ssh"
      - ansible_connection is defined and ansible_connection != "smart"
      - ansible_connection is defined and ansible_connection != "lxd"
  when:
    - ansible_host != "localhost"
    # - ansible_facts['env']['USER'] == a_cm_user
    # - cm_user == a_cm_user
    # user account to sync from must be available on control machine
    # - cm_user in a_control_machine_users

# option #3: using lxc file push for lxd connection
- import_tasks: account_dotfiles_copy_lxc.yml
  when:
    - ansible_connection is defined
    - ansible_connection == "lxd"

- name: try execute a users's Makefile found in dotfiles_dir
  make:
    chdir: "{{makefile_path|dirname}}"
    target: "{{item[1]|default(omit)}}"
  become_user: "{{item[0]['name']}}"
  loop: "{{users|subelements('dotfiles_makefile_targets',{'skip_missing': True})}}"
  # loop: "{{lookup('nested', users, dotfiles_makefiles_targets|default(['']))}}"
  when:
    - makefile_path is file
  vars:
    makefile_path: "{{item[0]['homedir']|default(users_defaults['homedir_root'] ~ '/' ~ item[0]['name'])}}/{{item[0]['dotfiles_dir']}}/Makefile"
