---

- name: install 'users_default_domain' 'public ssh keys' on matching domains
  authorized_key:
    user: "{{item.name}}"
    key: "{{lookup('file', groups_dir ~ '/' ~ usergroup.name ~ '/keys/' ~ item.name ~ '.' ~ users_default_domain ~ '.pub')}}"
    exclusive: "{{users_exclusive_ssh_keys}}"
  with_items:
    - "{{users|default(omit)}}"
  when: users_default_domain is defined and users_default_domain == ansible_domain

- name: install ssh_domains extra 'public ssh keys' on matching domains
  authorized_key:
    user: "{{item.0.name}}"
    key: "'{{lookup('file', groups_dir ~ '/' ~ usergroup.name ~ '/keys/' + ~ item.name ~ '.' ~ item.1 ~ '.pub')}}'"
    exclusive: "{{users_exclusive_ssh_keys}}"
  with_subelements:
    - "{{users|selectattr('ssh_domains','defined')|list|default(omit)}}"
    - ssh_domains
  when: item.1 == "item.0.name + ansible_fqdn"
