---

- name: rsync dotfiles to target host user account
  synchronize:
    delete: yes
    src: "{{item.home|default(users_defaults.home)}}/{{item.name}}/{{item.dotfiles_dir}}"
    dest: "{{item.home|default(users_defaults.home)}}/{{item.name}}/"
  become_user: "{{item.name}}"
  # become: no
  with_items: "{{users|selectattr('dotfiles_dir','defined')|list}}"

- name: rsync .vim directory to target host user account
  synchronize:
    delete: yes
    src: "{{item.home|default(users_defaults.home)}}/{{item.name}}/{{item.vim_dir}}"
    dest: "{{item.home|default(users_defaults.home)}}/{{item.name}}/"
  become_user: "{{item.name}}"
  # become: no
  with_items: "{{users|selectattr('vim_dir','defined')|list}}"
