---

# useful when ansible_connection != ssh => (can't use rsync and synchronize)
- name: copy dotfiles to target host user account
  copy:
    src: "{{item.home|default(users_defaults.home)}}/{{item.name}}/{{item.dotfiles_dir}}"
    dest: "{{item.home|default(users_defaults.home)}}/{{item.name}}/"
    owner: "{{item.name}}"
    group: "{{usergroup.name}}"
  with_items: "{{users|default(omit)|selectattr('dotfiles_dir','defined')|list}}"

- name: copy .vim directory to target host user account
  copy:
    src: "{{item.home|default(users_defaults.home)}}/{{item.name}}/{{item.vim_dir}}"
    dest: "{{item.home|default(users_defaults.home)}}/{{item.name}}/"
    owner: "{{item.name}}"
    group: "{{usergroup.name}}"
  with_items: "{{users|default(omit)|selectattr('vim_dir','defined')|list}}"
