---

# user public ssh keys fetching

- name: fetch {{ansible_domain}} public ssh keys back to control machine
  fetch:
    src: "{{item.home|default(users_defaults.home)}}/{{item.name}}/.ssh/{{item.name}}.{{ansible_domain}}.pub"
    dest: "{{groups_dir}}/{{usergroup.name}}/keys/"
    flat: yes
  loop:
    - "{{users}}"

- name: fetch extra 'ssh_domains' public ssh keys back to control machine
  fetch:
    src: "{{item.0.home|default(users_defaults.home)}}/{{item.0.name}}/.ssh/{{item.0.name}}.{{item.1}}.pub"
    dest: "{{groups_dir}}/{{usergroup.name}}/keys/"
    flat: yes
  loop: lookup('subelements',  "{{users|selectattr('ssh_domains','defined')|list}}", ssh_domains)
  when: item.1
