---

# Prior to executing this task, we have moved existing keypairs to avoid
# ssh-keygent runtime error while attempting to overwrite a keyfile. Be
# careful moving this task around. We can safely do an union because we
# registered expired key *after* deletion of unmanaged keypairs. We are now
# sure to not recreate an expired keys that became also unmanaged.
# However if examining lists content on check run '-C' will be slightly
# wrong.

# ssh-keygen reminder:
#    -N new_passphrase
#    -q quiet
#    -f filename

  # fixme: warning when undefined new_ssh_keys
- name: generate new ssh keys
  command: ssh-keygen -q -N 'changeme' -f ~/.ssh/{{item.0.user}}.{{item.1}}
  become_user: "{{item.0.user}}"
  with_subelements:
    - "{{new_ssh_keys}}"
    - ssh_domains
