---

- name: register raw list of {{usergroup['name']}} active ssh keys
  find:
    paths: "{{groups_dir}}/{{usergroup['name']}}/keys"
    patterns: "*.pub"
  register: raw_active_ssh_keys

# all those are flat lists to allow usage built-in theory filters
# managed_ssh_keys: flat list of keys for all usergroup users as defined in
#                   users.yml and considering 'users_default_domain'.
# active_ssh_keys: flat list of keys already in place (from list of pub keys on
#                 control machine
- name: set '{{usergroup['name']}}' 'managed' and 'active' ssh key lists
  set_fact:
    managed_ssh_keys: "{{users|get_managed_keys(users_default_domain)}}"
    active_ssh_keys: "{{raw_active_ssh_keys.files|map(attribute='path')|get_ssh_keylist}}"

# # run ansible with "-e 'groupadd_debug=True'
- include_tasks: ssh_key_debug.yml
  when: groupadd_debug and users_generate_ssh_keys is defined and unmanaged_ssh_keys is defined
